In [24]:
import numpy as np
import pandas as pd

data = np.random.randn(5,5)
dataFrame = pd.DataFrame(data)
print(dataFrame)
print()
newdataFrame = pd.DataFrame(data,index=["Esad","Bulent","Muazzez","Oya","Miray"],columns=["First","Second","Third","Fourth","Fifth"])
print(newdataFrame)
print()
print(newdataFrame.loc["Esad"])
print()
print(newdataFrame.iloc[2])
print()
newdataFrame["Sixth"] = newdataFrame["Second"] + newdataFrame["Fifth"]
print(newdataFrame)
print()
newdataFrame.drop("Second",axis = 1)
print(newdataFrame)
print()
newdataFrame.drop("Second",axis = 1,inplace=True)
print(newdataFrame)
print()
print(newdataFrame < 0)
print()
print(newdataFrame > 0)
print()
print(newdataFrame[newdataFrame < 0])
print()
print(newdataFrame[newdataFrame > 0])
print()
print(newdataFrame[newdataFrame["Fourth"] > 0])
print()
print(newdataFrame[newdataFrame["First"] > 0])

          0         1         2         3         4
0 -2.104187 -0.249217 -0.810265  1.124670 -1.351349
1  0.750050  0.121755  1.010904 -0.635225 -0.202503
2 -0.333790  0.730491  0.050875  1.265795  0.454239
3 -0.116420  1.069915 -1.033136  1.272782  0.092970
4  0.337587 -1.331489 -0.370061  0.098512  0.747182

            First    Second     Third    Fourth     Fifth
Esad    -2.104187 -0.249217 -0.810265  1.124670 -1.351349
Bulent   0.750050  0.121755  1.010904 -0.635225 -0.202503
Muazzez -0.333790  0.730491  0.050875  1.265795  0.454239
Oya     -0.116420  1.069915 -1.033136  1.272782  0.092970
Miray    0.337587 -1.331489 -0.370061  0.098512  0.747182

First    -2.104187
Second   -0.249217
Third    -0.810265
Fourth    1.124670
Fifth    -1.351349
Name: Esad, dtype: float64

First    -0.333790
Second    0.730491
Third     0.050875
Fourth    1.265795
Fifth     0.454239
Name: Muazzez, dtype: float64

            First    Second     Third    Fourth     Fifth     Sixth
Esad    -2.104187 -0.249217 -0.810265  1.124670 -1.351349 -1.600567
Bulent   0.750050  0.121755  1.010904 -0.635225 -0.202503 -0.080748
Muazzez -0.333790  0.730491  0.050875  1.265795  0.454239  1.184730
Oya     -0.116420  1.069915 -1.033136  1.272782  0.092970  1.162885
Miray    0.337587 -1.331489 -0.370061  0.098512  0.747182 -0.584306

            First    Second     Third    Fourth     Fifth     Sixth
Esad    -2.104187 -0.249217 -0.810265  1.124670 -1.351349 -1.600567
Bulent   0.750050  0.121755  1.010904 -0.635225 -0.202503 -0.080748
Muazzez -0.333790  0.730491  0.050875  1.265795  0.454239  1.184730
Oya     -0.116420  1.069915 -1.033136  1.272782  0.092970  1.162885
Miray    0.337587 -1.331489 -0.370061  0.098512  0.747182 -0.584306

            First     Third    Fourth     Fifth     Sixth
Esad    -2.104187 -0.810265  1.124670 -1.351349 -1.600567
Bulent   0.750050  1.010904 -0.635225 -0.202503 -0.080748
Muazzez -0.333790  0.050875  1.265795  0.454239  1.184730
Oya     -0.116420 -1.033136  1.272782  0.092970  1.162885
Miray    0.337587 -0.370061  0.098512  0.747182 -0.584306

         First  Third  Fourth  Fifth  Sixth
Esad      True   True   False   True   True
Bulent   False  False    True   True   True
Muazzez   True  False   False  False  False
Oya       True   True   False  False  False
Miray    False   True   False  False   True

         First  Third  Fourth  Fifth  Sixth
Esad     False  False    True  False  False
Bulent    True   True   False  False  False
Muazzez  False   True    True   True   True
Oya      False  False    True   True   True
Miray     True  False    True   True  False

            First     Third    Fourth     Fifth     Sixth
Esad    -2.104187 -0.810265       NaN -1.351349 -1.600567
Bulent        NaN       NaN -0.635225 -0.202503 -0.080748
Muazzez -0.333790       NaN       NaN       NaN       NaN
Oya     -0.116420 -1.033136       NaN       NaN       NaN
Miray         NaN -0.370061       NaN       NaN -0.584306

            First     Third    Fourth     Fifth     Sixth
Esad          NaN       NaN  1.124670       NaN       NaN
Bulent   0.750050  1.010904       NaN       NaN       NaN
Muazzez       NaN  0.050875  1.265795  0.454239  1.184730
Oya           NaN       NaN  1.272782  0.092970  1.162885
Miray    0.337587       NaN  0.098512  0.747182       NaN

            First     Third    Fourth     Fifth     Sixth
Esad    -2.104187 -0.810265  1.124670 -1.351349 -1.600567
Muazzez -0.333790  0.050875  1.265795  0.454239  1.184730
Oya     -0.116420 -1.033136  1.272782  0.092970  1.162885
Miray    0.337587 -0.370061  0.098512  0.747182 -0.584306

           First     Third    Fourth     Fifth     Sixth
Bulent  0.750050  1.010904 -0.635225 -0.202503 -0.080748
Miray   0.337587 -0.370061  0.098512  0.747182 -0.584306